Added username and .html file
muan/hello-world pull request #146
Opened 2017-10-29 15:40 UTC by ap1459

Added name to human.txt and .html file to humans folder.

2017-10-30 06:05 UTC, SubhrajyotiSen requested changes
Please remove the .DS_Store files

2017-10-30 13:18 UTC, ap1459 commented
Hello, I believe I have now removed the files. Please let me know if not and I will rectify.

2018-02-09 14:13 UTC, aaossa commented
Ups, it seems like this is ok now, I'll squash and merge later 👌 Can you update your review @SubhrajyotiSen ?

2018-02-09 14:13 UTC, aaossa approved these changes

2018-02-11 04:18 UTC, SubhrajyotiSen approved these changes

2018-02-11 04:18 UTC, merged