Create flarelina
muan/hello-world pull request #175
Opened 2018-07-25 05:44 UTC by flarelinaa

Hi this is my very first pull request on your repository

2018-07-25 07:27 UTC, leewp14 requested changes
Hi @flarelinaa , thank you for your pull request! 
However, minor changes are needed to have your pull request merged : 
 - the file name needs to be the same as your GitHub username, in this case, is `flarelinaa`
 - you might want to consider adding your username to human.txt

Cheers :smiley:

2018-07-26 06:04 UTC, flarelinaa commented
Hi @leewp14, thank you for reviewing my pull request.

2018-07-26 10:12 UTC, leewp14 approved these changes

2018-07-26 10:13 UTC, merged

2018-07-26 10:18 UTC, leewp14 commented
You're welcome, @flarelinaa. Welcome to GitHub! :smile: