test pull request
muan/hello-world pull request #234
Opened 2022-01-21 08:58 UTC by Azlur

2022-01-21 09:09 UTC, leewp14 requested changes, later dismissed
Hi @Azlur , thanks for your pull request! It's more preferrable to have usernames positioned according to alphabetical order, kindly update your pull request to reflect the necessary changes. Looking forward to your updated PR :smiley:

2022-01-21 09:09 UTC, leewp14 commented on human.txt
> +Azlur
This should be positioned somewhere near the start of this file as according to alphabetical order.

2022-01-21 09:22 UTC, Azlur commented
I have positionned my username in alphabetic order

2022-04-25 05:09 UTC, muan approved these changes

2022-04-25 05:10 UTC, merged