Pull request !
muan/hello-world pull request #235
Opened 2022-02-24 19:44 UTC by Abhijeetbyte

Hi, intrested to maintain and merge a pull request

2022-04-19 12:29 UTC, robjames26 approved these changes

2022-04-19 12:30 UTC, robjames26 approved these changes

2022-04-19 12:30 UTC, robjames26 approved these changes

2022-04-19 12:30 UTC, robjames26 approved these changes

2022-04-25 04:25 UTC, Abhijeetbyte commented
@robjames26 , thanks

but it still says : 
**Review required**
**Merging is blocked**

2022-04-25 05:08 UTC, muan requested changes

2022-04-25 05:08 UTC, muan commented on human.txt
> +Abhijeet
This should be your username instead.

2022-04-26 17:20 UTC, Abhijeetbyte commented on human.txt
> +Abhijeetbyte
oh, it's done !

2022-04-26 17:22 UTC, Abhijeetbyte commented
@muan , requested changes done !

kindly review and merge

2022-06-04 08:04 UTC, Abhijeetbyte commented
@muan you are requested to review changes. 
So Merging can be performed

2022-08-01 10:03 UTC, Abhijeetbyte commented on human.txt
> +Abhijeet
@muan it's done ! kindly merge

2022-08-10 10:47 UTC, muan approved these changes

2022-08-10 10:48 UTC, merged

2022-08-10 10:48 UTC, muan commented
Sorry for the delay!

2022-08-10 10:49 UTC, Abhijeetbyte commented
> Sorry for the delay!

**it's alright**