translated readme to two more languages
muan/hello-world pull request #89
Opened 2017-04-04 19:05 UTC by pmayur

translated readme to two new languages:

- hindi
- marathi

2017-04-10 17:21 UTC, SubhrajyotiSen commented
@pmayur Can you please fix the merge conflict? 😃 
@aaossa I can review the Hindi translation. I will try finding someone to verify the marathi one soon

2017-04-10 17:24 UTC, SubhrajyotiSen requested changes

2017-04-10 17:24 UTC, SubhrajyotiSen commented on human.txt
> +pmayur
This has already been added in #88

2017-04-10 17:29 UTC, aaossa commented
Thanks @SubhrajyotiSen :ok_hand: I don't know those languages, but I knew that you were a good reviewer for this :raised_hands:

2017-04-11 12:43 UTC, pmayur commented on human.txt
> +pmayur
I think my pmayur.html which happens to be my html file is conflicting where I made some changes intentionally. If thats not the problem can you help me with resolving the conflict?

2017-04-11 12:53 UTC, aaossa commented
I fixed the conflicts, but will wait until @SubhrajyotiSen  say everything is OK 👍

2017-04-11 13:08 UTC, SubhrajyotiSen commented
The Hindi translation is good. I am still looking for a person to review the marathi one.
@pmayur Just a suggestion. In the future, try to keep such commits in differrent PRs. For example, if you had made two separate PRs for Hindi and Marathi, I could have merged the Hindi one right now. But in the current case, the PR will have to wait till Marathi is reviwed.

2017-04-11 13:29 UTC, pmayur commented
Well yeah thankyou ! these are the very first of my contributions so lesson learnt, thanks for the suggestion.

2017-05-02 12:01 UTC, aaossa commented
Any updates on this?

2017-05-02 12:21 UTC, SubhrajyotiSen commented
Unfortunately, I was not able to find anyone to verify the marathi translation

2017-05-02 12:24 UTC, aaossa commented
Well, I think we could trust. That's the first step in OSS development isn't it? I'll give my 👍

2017-05-02 12:25 UTC, aaossa approved these changes
LGTM :sparkles:

2017-05-02 12:30 UTC, SubhrajyotiSen approved these changes

2017-05-02 12:38 UTC, merged

2017-05-02 12:40 UTC, SubhrajyotiSen commented
@pmayur Thanks for the translations 😃

2017-05-02 13:35 UTC, pmayur commented
thanks to you guys too  !